apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: albertohco/conversao:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
